name: Web UI

on:
  pull_request:
    branches:
      - maintenance-2.4.x
  # workflow_call:
  #   inputs:
  #     branch:
  #       description: 'The current branch'
  #       default: maintenance-3.0.x
  #       type: string
  #       required: false
  #   secrets:
  #     WEBUI_ACCESS_TOKEN_PERSONAL:
  #       description: 'WEBUI_ACCESS_TOKEN_PERSONAL'
  #       required: true

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'maintenance-2.4.x' }}

jobs:
  web-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Web UI cross repo check
        uses: nuxeo/ui-team-gh-actions/trigger-workflow@dcf8be425447c7fb9cdd1e048585a6df905ed878
        with:
          owner: nuxeo
          repo: nuxeo-web-ui
          workflow-id: cross-repo.yaml
          access-token: ${{ secrets.WEBUI_ACCESS_TOKEN_PERSONAL }}
          branch-name: 'pr-checks-2.4.x'
          inputs: |
            branch_name: ${{ env.BRANCH_NAME }}
            hf_version: 56
            sauce_labs: true
            skip_ftests: false
            skip_unit_tests: false
            generate_metrics: false
