name: Lint

on:
  push:
    branches:
      - maintenance-2.4.x
  pull_request:
    branches:
      - maintenance-2.4.x
  workflow_call:
    inputs:
      branch:
        description: 'The branch to lint'
        default: maintenance-2.4.x
        type: string
        required: false
      is_downstream:
        description: 'Specifices the source of the task'
        default: false
        type: boolean
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        description: 'NPM_PACKAGES_TOKEN'
        required: true

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'maintenance-2.4.x' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Checkout the Nuxeo Elements repository
        if: ${{ inputs.is_downstream == true }}
        uses: actions/checkout@v2
        with:
          repository: nuxeo/nuxeo-elements
          path: nuxeo-elements
          fetch-depth: 1
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          scope: '@nuxeo'

      - run: npm install -g bower

      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          bower install && npm install

      - name: Link Nuxeo elements
        if: ${{ inputs.is_downstream == true }}
        run: |
          rm -rf bower_components/nuxeo-elements
          rsync -av --exclude='node_modules' --exclude='.git' --exclude='bower_components' ./nuxeo-elements bower_components

      - name: Lint
        run: npm run lint
